spring: 
   profiles: 
      active: 
      - dev 
--- 
spring: 
   profiles: dev 
   application: 
      name: microservicecloud-config-gjk-dev 
--- 
spring: 
   profiles: test 
   application: 
      name: microservicecloud-config-gjk-test 